# Generated by Django 3.2.9 on 2021-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
