# Generated by Django 3.2.9 on 2021-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_rename_author_advert_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
