# Generated by Django 3.2.9 on 2021-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_auto_20211112_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
